global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'devplatform'
    env: 'dev'

scrape_configs:
  - job_name: 'service-registry'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          service: 'service-registry'

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'gateway'

  - job_name: 'log-aggregation'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          service: 'log-aggregation'

  - job_name: 'feature-flag-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          service: 'feature-flag-service'

  - job_name: 'rate-limiter'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8084']
        labels:
          service: 'rate-limiter'

  - job_name: 'ab-testing-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']
        labels:
          service: 'ab-testing-service'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
